### PR TITLE
findET executable; Fix issues #50, #53, #55, and #56

### PR DESCRIPTION
**Pull request by texadactyl**
Also, patched setup.py so that we can avoid the sqlite "database locked" failures when running ```pytest```.
Need to find a way to run the pytest coverage plugin without these failures.

### CODE REVIEW

**Comment by telegraphic** [comment]
#50  - All GPU device to be chosen by ID ✅ 
#53 - I like where this is going, but I think I'd prefer log level to be set by `hyperseti.set_log_level()` or similar ❓ 
#55 - Good catch ⚾ ✅ 
#56 - Ha! 👽 ✅  (We'll need to keep this updated though, still working on the pipeline so might need some API changes longer term)

**Comment by telegraphic** [comment]
Nice work @texadactyl , I'm happy with all but have a question on #53, as I'd prefer to see logger control kept separate to the main function calls

**Comment by texadactyl** [comment]
Regarding issue #53, are you saying that you'd prefer independent control in each main function?  Then, how would those logger levels be controlled by the user?

I can see an advantage of different granularities of logging but how does one manage that in a practical sense?

**Comment by telegraphic** [comment]
@texadactyl , what I meant was that you'd do something like:

```python
hyperseti.set_log_level('info')
hyperseti.do_something()

hyperseti.set_log_level('debug', loggers={'hyperseti.dedoppler'})
hyperseti.do_something()

```

i.e. keep the logger setup out of the signal processing function calls (I see how 'main function calls' was misleading).

**Comment by texadactyl** [comment]
How about this?

**Comment by texadactyl** [comment]
@telegraphic I think that your logging concenrns have been addressed.

**Pull request merged**
